### ISSUE TITLE
Potential replay attack against proofOfPossession()?

### ISSUE THREAD

**Issue by venezuela01** [oxen-io/eth-sn-contracts#6]
The C++ component of `eth-sn-contracts` is still a work in progress, the complete design is not fully clear.

Based on the test suite, there appears to be a lack of consideration for the risk of replay attacks. This is observed in the `proofOfPossession(uint32_t chainID, const std::string& contractAddress)` function in the `ServiceNode` class, which only utilizes `chainID` and `contractAddress` as its parameters.

Is this a valid concern, or am I being overly concerned? If a sophisticated attacker, capable of modifying Oxen C++ code, stakes a service node and then unstakes later, could they reuse an 'expired' `proofOfPossession`? In the absence of unique, time-bound elements such as nonces or block Id in the proof, would there be a risk of replay attacks?

**Comment by darcys22** [comment]
Yeah this legitimate and being discussed, there is a potential grieving attack where if you deregister your node an attacker could prevent you from reregistering. 

We will resolve this but its pretty minor cause the attacker would have to stake SENT (and risk losing it when we liquidate it) simply to force a user to recreate a new bls key.

**Comment by darcys22** [comment]
It’s not built yet and master branch is the latest version. Will link to the PR when resolved
